--- 
framework: mocha
postMerge: 
  pattern: 
    - ./test/**/*.spec.ts
postRun: 
  command: 
    - "node --version"
preMerge: 
  pattern: 
    - ./test/**/*.spec.ts
preRun: 
  command: 
    - "npm ci --ignore-scripts"
    - "npm run build"
version: 1.0
