---
framework: mocha
postMerge:
  pattern:
    - "./test/**/*.spec.ts"
preMerge:
  pattern:
    - "./test/**/*.spec.ts"
preRun:
     command:
        - npm ci --ignore-scripts
        - npm run build
postRun:
     command:
        - node --version
version: 1.0
